# Generated by Django 6.0.4 on 2026-04-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme_recrutement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruteur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recruteurs/'),
        ),
    ]
