# Generated by Django 6.0.4 on 2026-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme_recrutement', '0005_offre_competences_offre_date_limite_offre_lieu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='salaire',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
