# Generated by Django 6.0.4 on 2026-04-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme_recrutement', '0002_recruteur_photo'),
    ]

    operations = []
