# Generated by Django 6.0.4 on 2026-04-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme_recrutement', '0008_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='entretien_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='entretien_heure',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='entretien_lieu',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='candidature',
            name='entretien_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
