# Generated by Django 6.0.4 on 2026-04-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme_recrutement', '0009_candidature_entretien_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidature',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'en_attente')), fields=('offre', 'candidat'), name='unique_pending_candidature_per_offre_candidat'),
        ),
    ]
