# Generated by Django 6.0.4 on 2026-04-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme_recrutement', '0010_alter_candidature_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='entretien_type',
            field=models.CharField(blank=True, choices=[('online', 'En ligne'), ('onsite', 'Sur site')], default='', max_length=20),
        ),
    ]
