# Generated by Django 6.0.4 on 2026-04-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme_recrutement', '0011_candidature_entretien_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='entretien_type',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybride'), ('onsite', 'Sur site')], default='', max_length=20),
        ),
    ]
