# Generated by Django 6.0.4 on 2026-04-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme_recrutement', '0004_alter_offre_type_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='competences',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='offre',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='lieu',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='offre',
            name='salaire',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='offre',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Alternance', 'Alternance')], default='', max_length=20),
        ),
    ]
