# Generated by Django 6.0.4 on 2026-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme_recrutement', '0006_alter_offre_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidats/'),
        ),
    ]
